# Generated by Django 4.0.4 on 2022-05-28 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('information', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('city', models.CharField(max_length=50)),
                ('is_published', models.BooleanField()),
                ('links', models.JSONField()),
                ('organised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('AVERAGE_OF_5', 'Average Of 5'), ('MEAN_OF_3', 'Mean Of 3')], max_length=30)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.contest')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt1', models.FloatField()),
                ('attempt2', models.FloatField()),
                ('attempt3', models.FloatField()),
                ('attempt4', models.FloatField()),
                ('attempt5', models.FloatField()),
                ('best', models.FloatField()),
                ('average', models.FloatField()),
                ('pos', models.SmallIntegerField()),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.round')),
            ],
        ),
    ]
